deepseek_key = ""
model = "deepseek-chat"
url = "https://api.deepseek.com"
max_context_num = 10
# [mcp]
# server = [
#     {name = "fetch", protocol = "stdio", command = "node", args = [
#         "***"
#     ]}
# ]